SELECT A.USER_ID, A.PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(PRODUCT_ID) AS CNT
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
) A
WHERE A.CNT > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC
