SELECT A.ID, A.NAME, A.HOST_ID 
FROM PLACES A RIGHT JOIN 
(
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) >= 2
) B
ON A.HOST_ID = B.HOST_ID
WHERE A.HOST_ID IS NOT NULL
ORDER BY ID ASC
